[phases.setup]
nixPkgs = [
    "php83",
    "php83Extensions.pdo",
    "php83Extensions.pdo_pgsql",
    "php83Extensions.redis",
    "php83Extensions.gd",
    "php83Extensions.mbstring",
    "php83Extensions.xml",
    "php83Extensions.zip",
    "php83Extensions.curl",
    "php83Extensions.tokenizer",
    "php83Extensions.fileinfo",
    "php83Extensions.exif",
    "php83Extensions.bcmath",
    "php83Extensions.intl",
    "nodejs_22",
    "which"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci --ignore-scripts",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan storage:link",
    "php artisan config:cache",
    "php artisan event:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
